FROM node:16.18.1-alpine
EXPOSE 3000
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY . .
RUN npm install
CMD ["npm", "start"]
